services:
  database:
    image: postgres:18-alpine
    container_name: CloneTabnewsDB
    restart: always
    environment:
      POSTGRES_DB: cloneTabnews
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../clone-tabnews-data/db:/var/lib/postgresql

volumes:
  postgres_data:

